### PR TITLE
Ch config eslint 184637122

### PR DESCRIPTION
**Pull request by nkurunziza1**
**Description**

-This pull request add eslint configuration file to project . the configuration is designed to enforce consistent code style and best practices, and includes rules for Node.js, ES6, and Mocha.

**Testing**

The eslint configuration has been tested locally with the following command:

`eslint .`

**Cheklist**

-The code has been tested locally and pass the test

### CODE REVIEW

**Review by mjeanbosco19 — CHANGES_REQUESTED** [review]
Great job @nkurunziza1 
Please add coverage in gitignore

**Comment by Abdulkeza** [comment]
> Great job @nkurunziza1 Please add coverage in gitignore

he already has coverage in gitignore, but the rest of you before pushing delete the coverage folder.

**Review by JENNY-257 — APPROVED** [review]

**Review by katros1 — APPROVED** [review]
I have check your task, eslint is well configured, but I think there are some rules you need to make off or warn  instead of error like "semi", "no-console" and others which u see they are not necessary, so that they won't cause confusion to others

**Review by ba-lambert — COMMENTED** [review]
Why do you use chai for expectations?? I think chai is the same as jest and we have choose Jest

**Review by leandreAlly — APPROVED** [review]

**Review by Abdulkeza — APPROVED** [review]

**Pull request merged**
